apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: galaxy2
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: galaxy
    helm.sh/chart: galaxy-3.5.4
  name: lammps-galaxy-pvc
  namespace: galaxy2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
