apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: ubuntu-desk-vmd
  name: ubuntu-desk-vmd-svc
  namespace: galaxy2
spec:
  ports:
  - port: 6080
    targetPort: 80
    nodePort: 30008
  selector:
    k8s-app: ubuntu-desk-vmd
  type: NodePort
