## Here, helm keeps track of the dependencies that are required for the
## application. Dependencies should be listed here, then the dependencies
## updated with:
##
##    helm dep update
##
## and the requirements.lock file committed.
dependencies:
    - name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.1.4
      condition: postgresql.enabled
