kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: galaxy-default-rbac
subjects:
- kind: ServiceAccount
  name: default
  namespace: galaxy2
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
