apiVersion: apps/v1
kind: Deployment
metadata:
  name: planemo-deploy
  namespace: galaxy2
  labels:
    k8s-app: planemo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: planemo-deploy
  template:
    metadata:
      labels:
        k8s-app: planemo-deploy
    spec:
      containers: 
      - name: planemo-deploy
        image: 192.168.108.107:5000/planemo:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        command: ["/bin/bash"]
        args: ["-c","source /etc/profile;tail -f /dev/null"]
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
